version: '3.8'
services:
  chiko-app:
    build:
      context: ./Chiko 
      dockerfile: Dockerfile
    command: mvn spring-boot:run
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://chiko-db:5432/chiko
      SPRING_DATASOURCE_USERNAME: saadal-ageel
      SPRING_DATASOURCE_PASSWORD: saad 
    depends_on:
      - chiko-db

  chiko-db:
    image: postgres:16
    environment:
      POSTGRES_DB: chiko
      POSTGRES_USER: saadal-ageel 
      POSTGRES_PASSWORD: saad 
    volumes:
      - ./backup.sql:/docker-entrypoint-initdb.d/backup.sql
    ports:
      - "5432:5432"

  chiko-react-app:
    build:
      context: ./frontend/cheko/ 
      dockerfile: Dockerfile
    command: yarn start
    ports:
      - "3000:3000"
    depends_on:
      - chiko-app

volumes:
  postgres_data:
